<a href="https://colab.research.google.com/github/Laurarpoa/Grupo-de-trabajo-/blob/main/Parcial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Parcial 1. Laura Restrepo, Tatiana Monteagudo, Mateo Marín, Esteban Ramirez

import numpy as np
import pandas as pd


In [ ]:
#1. Crea un array de NumPy con los números del 1 al 100 e imprime los múltiplos de 7.

arr1=np.arange(1,101)
print("Múltiplos de 7:")
print(arr1[arr1%7==0])

Múltiplos de 7:
[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]


In [ ]:
#2. Crea una matriz de 4x4 con números aleatorios enteros entre 10 y 50. Luego reemplaza los valores impares por -1.

matriz1 = np.random.randint(10,51,size=(4,4))
print(matriz1)

matriz1[matriz1%2!=0] = -1
print("\nNúmeros impares(-1)")
print (matriz1)

[[12 37 35 39]
 [22 22 11 46]
 [47 11 45 35]
 [20 17 49 31]]

Números impares(-1)
[[12 -1 -1 -1]
 [22 22 -1 46]
 [-1 -1 -1 -1]
 [20 -1 -1 -1]]


In [ ]:
#3. Genera una matriz de 5x5 con valores entre 0 y 1 distribuidos uniformemente. Luego, calcula la suma por columnas.

matriz2 = np.random.uniform(0,1,size=(5,5))
print(matriz2)

suma_columnas = np.sum(matriz2,axis=0)
print("\nSuma de columnas:")
print(suma_columnas)

[[0.67753161 0.37312262 0.94169199 0.16735703 0.50035945]
 [0.69088398 0.69713581 0.64863896 0.27528821 0.15620657]
 [0.63594033 0.59930212 0.17935601 0.70513915 0.45517199]
 [0.66776059 0.83736708 0.16972843 0.01914487 0.77910259]
 [0.60969743 0.69963957 0.83815497 0.80281093 0.96092015]]

Suma de columnas:
[3.28181393 3.20656719 2.77757036 1.96974019 2.85176074]


In [ ]:
#4. Dado un array arr = np.array([1, 2, 3, 4, 5]), obtén su versión invertida.

arr2 = np.array([1,2,3,4,5])
print(arr2)

arr2_invertido = arr2[::-1]
print("Array invertido:",(arr2_invertido))

[1 2 3 4 5]
Array invertido: [5 4 3 2 1]


In [ ]:
#5. Crea una matriz identidad de 6x6 y multiplícala por 3. ¿Qué observas?

matriz3 = np.eye(6)
print(matriz3)

matriz3 = matriz3*3
print("\nMatriz multiplicada por 3:")
print(matriz3)

#Los 1 fueron reemplazados por 3, sigue siendo diagonal.

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Matriz multiplicada por 3:
[[3. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]


In [ ]:
#6. Crea un array de 15 elementos entre 1 y 100 y ordénalo de mayor a menor.

arr3 = np.random.randint(1,101,size=(15))
print(arr3)

arr3_ordenado = np.sort(arr3)[::-1]
print("\nArray ordenado de mayor a menor:")
print(arr3_ordenado)

[21 12 50  4 42 84 38 25 14 75 32 11 61 18 27]

Array ordenado de mayor a menor:
[84 75 61 50 42 38 32 27 25 21 18 14 12 11  4]


In [ ]:
#7. Usa NumPy para calcular la media, la mediana y la desviación estándar de un array de 30 valores aleatorios entre 0 y 100.

arr4 = np.random.randint(0,101,size=(30))
print(arr4)

media = np.mean(arr4)
print("\nMedia:")
print(media)

mediana = np.median(arr4)
print("\nMediana:")
print(mediana)

std = np.std(arr4)
print("\nDesviación estándar:")
print(std)

[79 68 84  9 82 24 67 60 28 18 42 65 73 60 42 24 19 47 82 86 23 10 97 54
 27 68 62 58  4 50]

Media:
50.4

Mediana:
56.0

Desviación estándar:
25.99564066018249


In [ ]:
#8. Crea un array bidimensional 6x3 con valores aleatorios y reemplaza la fila con el menor promedio por ceros.

arr5 = np.random.rand(6,3)
print(arr5)

fila_menor = np.argmin(np.mean(arr5,axis=1))
arr5[fila_menor] = 0
print("\nFila con el menor promedio reemplazada por ceros:")
print(arr5)

[[0.85812039 0.78377239 0.42898493]
 [0.20106515 0.51420104 0.73622888]
 [0.4364196  0.66677191 0.09432743]
 [0.74800474 0.81271362 0.70683786]
 [0.96726359 0.82665206 0.90309373]
 [0.93357108 0.80134799 0.67425884]]

Fila con el menor promedio reemplazada por ceros:
[[0.85812039 0.78377239 0.42898493]
 [0.20106515 0.51420104 0.73622888]
 [0.         0.         0.        ]
 [0.74800474 0.81271362 0.70683786]
 [0.96726359 0.82665206 0.90309373]
 [0.93357108 0.80134799 0.67425884]]


In [ ]:
#9. Crea un array 3x4 y aplica la función np.cumsum().

arr6 = np.random.rand(3,4)
print(arr6)

arr6_filas = np.cumsum(arr6,axis=1)
print("\nArray con la función np.cumsum() por filas:")
print(arr6_filas)

arr6_columnas = np.cumsum(arr6,axis=0)
print("\nArray con la función np.cumsum() por columnas:")
print(arr6_columnas)

[[0.98330566 0.78670834 0.77366256 0.74783857]
 [0.1506081  0.21723089 0.46399013 0.26400435]
 [0.41524097 0.88846411 0.82432689 0.63003988]]

Array con la función np.cumsum() por filas:
[[0.98330566 1.770014   2.54367656 3.29151514]
 [0.1506081  0.36783899 0.83182912 1.09583347]
 [0.41524097 1.30370508 2.12803197 2.75807185]]

Array con la función np.cumsum() por columnas:
[[0.98330566 0.78670834 0.77366256 0.74783857]
 [1.13391376 1.00393923 1.2376527  1.01184292]
 [1.54915473 1.89240334 2.06197959 1.6418828 ]]


In [ ]:
#10. Dado el siguiente array:
#   arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# Extrae solo los elementos de la diagonal principal.

arr7 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr7)

diagonal = np.diagonal(arr7)
print("\nDiagonal principal:")
print(diagonal)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

Diagonal principal:
[10 50 90]


In [ ]:
#11. Crea un DataFrame con las columnas: Nombre, Edad, Ciudad, Salario con al menos 5 registros. Filtra los registros con salario mayor a 2.000.000.

# Crear el DataFrame
data = {
    'Nombre': ['Camila', 'Sigilfredo', 'Raul', 'Ernesto', 'Juan', 'Axel','Ricardo','Eva','Alicia','Gloria'],
    'Edad': [18, 24, 65, 70,30,22,57,78, 44, 33],
    'Ciudad': ['Santander', 'Ocaña', 'San andres', 'Barranquilla', 'Cartagena','Popayan','Cali','Medellin','Turbo','Santa Marta' ],
    'Salario': [1800000, 2500000, 2200000, 1900000, 3000000,5500000,1000000,9900000,3800000,6700000]
}

df = pd.DataFrame(data)

# Filtrar los registros con salario mayor a 2.000.000
salario_alto = df[df['Salario'] > 2000000]
print(salario_alto)

       Nombre  Edad       Ciudad  Salario
1  Sigilfredo    24        Ocaña  2500000
2        Raul    65   San andres  2200000
4        Juan    30    Cartagena  3000000
5        Axel    22      Popayan  5500000
7         Eva    78     Medellin  9900000
8      Alicia    44        Turbo  3800000
9      Gloria    33  Santa Marta  6700000


In [ ]:
#12. Importa un CSV desde una URL o archivo local y muestra las 10 primeras filas y las 5 últimas.

# URL de ejemplo con datos públicos
url = "https://www.datos.gov.co/resource/fgk8-hnys.csv"

# Leer el archivo CSV desde la URL
df = pd.read_csv(url)

# Mostrar las 10 primeras filas
print("Primeras 10 filas:")
print(df.head(10))

# Mostrar las 5 últimas filas
print("\nÚltimas 5 filas:")
print(df.tail(5))

Primeras 10 filas:
   codigoprestador  codigohabilitacionsede  ese naturalezajuridica  \
0       9100100019            912630001911   SI            Pública   
1       9100100019            914050001914   SI            Pública   
2       9100100019            914070001915   SI            Pública   
3       9100100019            914300001916   SI            Pública   
4       9100100017            910010001701  NaN            Privada   
5       9100100019            910010001901   SI            Pública   
6       9100100022            910010002201   NO            Pública   
7       9100100036            910010003601   NO            Privada   
8       9100100037            910010003701   NO            Privada   
9       9100100038            910010003801   NO            Privada   

                                      claseprestador  \
0  Instituciones Prestadoras de Servicios de Salu...   
1  Instituciones Prestadoras de Servicios de Salu...   
2  Instituciones Prestadoras de Servicios 

In [ ]:
#13. A partir de un DataFrame con una columna de fechas, crea una nueva columna con el nombre del mes.

# Crear un DataFrame con fechas
data = {
    'Fecha': ['2002-10-28', '2004-03-13', '2025-07-22', '2000-09-18', '1969-10-17', '1969-04-27']
}
df = pd.DataFrame(data)

# Convertir la columna 'Fecha' a tipo datetime
df['Fecha'] = pd.to_datetime(df['Fecha'])

# Crear nueva columna con el nombre del mes
df['Mes'] = df['Fecha'].dt.strftime('%B')
print(df)

       Fecha        Mes
0 2002-10-28    October
1 2004-03-13      March
2 2025-07-22       July
3 2000-09-18  September
4 1969-10-17    October
5 1969-04-27      April


In [ ]:
#14. Agrupa un DataFrame por la columna Ciudad y calcula el salario promedio por ciudad.

# Crear el DataFrame de ejemplo
data = {
    'Nombre': ['Evelyn', 'Ricardo', 'Jose', 'Marlon', 'Tatiana', 'Santiago','Mateo','David','Blanca','Leidy'],
    'Edad': [18, 24, 65, 70,30,22,57,78, 44, 33],
    'Ciudad': ['Santander', 'Ocaña', 'Santander', 'Cartagena', 'Cartagena','Ocaña','Cali','Medellin','Medellin','Cartagena'],
    'Salario': [1850000, 2544000, 2257000, 8970000, 4532000,5546000,17860000,59430000,34890000,5700000]
}

df = pd.DataFrame(data)

# Agrupar por ciudad y calcular el salario promedio
salario_promedio = df.groupby('Ciudad')['Salario'].mean().reset_index()

# Renombrar la columna para mayor claridad
salario_promedio.columns = ['Ciudad', 'Salario Promedio']
print(salario_promedio)

      Ciudad  Salario Promedio
0       Cali      1.786000e+07
1  Cartagena      6.400667e+06
2   Medellin      4.716000e+07
3      Ocaña      4.045000e+06
4  Santander      2.053500e+06


In [ ]:
#15. Agrega una columna que indique si la persona es menor de 30 años (True o False).

# Crear el DataFrame de ejemplo
data = {
    'Nombre': ['Evelyn', 'Ricardo', 'Jose', 'Marlon', 'Tatiana', 'Santiago','Mateo','David','Blanca','Leidy'],
    'Edad': [18, 24, 65, 70,30,22,57,78, 44, 33],
    'Ciudad': ['Santander', 'Ocaña', 'Santander', 'Cartagena', 'Cartagena','Ocaña','Cali','Medellin','Medellin','Cartagena'],
    'Salario': [1850000, 2544000, 2257000, 8970000, 4532000,5546000,17860000,59430000,34890000,5700000]
    }
df = pd.DataFrame(data)

# Agregar la columna 'Menor_30'
df['Menor_30'] = df['Edad'] < 30
print(df)

     Nombre  Edad     Ciudad   Salario  Menor_30
0    Evelyn    18  Santander   1850000      True
1   Ricardo    24      Ocaña   2544000      True
2      Jose    65  Santander   2257000     False
3    Marlon    70  Cartagena   8970000     False
4   Tatiana    30  Cartagena   4532000     False
5  Santiago    22      Ocaña   5546000      True
6     Mateo    57       Cali  17860000     False
7     David    78   Medellin  59430000     False
8    Blanca    44   Medellin  34890000     False
9     Leidy    33  Cartagena   5700000     False


In [ ]:
#16. Reemplaza todos los valores nulos de una columna llamada Salario por el promedio de esa columna.

# DataFrame con algunos valores nulos en 'Salario'
data = {
    'Nombre': ['Max', 'Lisy', 'Edward', 'Martha', 'Carla'],
    'Salario': [2345000, np.nan, 2234500, 9867000, np.nan]
}

df = pd.DataFrame(data)

# Calcular el promedio de la columna 'Salario' (ignorando los NaN)
promedio_salario = df['Salario'].mean()

# Reemplazar los valores nulos con el promedio
df['Salario'] = df['Salario'].fillna(promedio_salario)
print(df)

   Nombre    Salario
0     Max  2345000.0
1    Lisy  4815500.0
2  Edward  2234500.0
3  Martha  9867000.0
4   Carla  4815500.0


In [ ]:
#17. Crea un DataFrame con columnas duplicadas y elimina las duplicadas dejando solo una copia.

# Crear un DataFrame con columnas duplicadas
df = pd.DataFrame([
    ['Evelyn', 34, 34, 'Bogotá'],
    ['Maria', 21, 21, 'Medellín'],
    ['Esperanza', 88, 88, 'Cali']
], columns=['Nombre', 'Edad', 'Edad', 'Ciudad'])  # dos columnas llamadas 'Edad'

# Mostrar el DataFrame con columnas duplicadas
print("Antes:")
print (df)

# Eliminar columnas duplicadas por nombre
df = df.loc[:, ~df.columns.duplicated()]

# Mostrar el DataFrame ya corregido
print("\nDespués:")
print(df)

Antes:
      Nombre  Edad  Edad    Ciudad
0     Evelyn    34    34    Bogotá
1      Maria    21    21  Medellín
2  Esperanza    88    88      Cali

Después:
      Nombre  Edad    Ciudad
0     Evelyn    34    Bogotá
1      Maria    21  Medellín
2  Esperanza    88      Cali


In [ ]:
#18. Ordena un DataFrame por dos columnas: primero por Ciudad alfabéticamente y luego por Edad de mayor a menor.

 # Crear un DataFrame de ejemplo
data = {
    'Nombre': ['Facundo', 'Federico', 'Tomas', 'Ezequiel', 'Vanessa', 'Estefania'],
    'Edad': [34, 12, 65, 56, 89,44],
    'Ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali', 'Medellín']
}

df = pd.DataFrame(data)

# Ordenar por 'Ciudad' (ascendente) y luego por 'Edad' (descendente)
df_ordenado = df.sort_values(by=['Ciudad', 'Edad'], ascending=[True, False])

print(df_ordenado)

      Nombre  Edad    Ciudad
3   Ezequiel    56    Bogotá
0    Facundo    34    Bogotá
4    Vanessa    89      Cali
2      Tomas    65      Cali
5  Estefania    44  Medellín
1   Federico    12  Medellín


In [ ]:
#19. Agrupa por Producto, calcula el ingreso total (Precio * Cantidad) por producto y ordénalo de mayor a menor.

# Crear el DataFrame
df = pd.DataFrame({
    'Producto': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Precio': [1200, 1500, 1300, 1000, 1600, 1250],
    'Cantidad': [3, 2, 5, 1, 2, 4]
})

# Calcular ingreso por fila (Precio * Cantidad)
df['Ingreso'] = df['Precio'] * df['Cantidad']

# Agrupar por producto y sumar ingresos
ingresos_por_producto = df.groupby('Producto')['Ingreso'].sum().reset_index()

# Ordenar de mayor a menor ingreso
ingresos_por_producto = ingresos_por_producto.sort_values(by='Ingreso', ascending=False)

print(ingresos_por_producto)

  Producto  Ingreso
0        A    15100
1        B     6200
2        C     1000


In [ ]:
#20. Con un DataFrame de 1000 registros de ventas simuladas (puedes generarlo con datos aleatorios que incluyan columnas como fecha, producto, cantidad, precio_unitario, zona), responde:

# Fijar semilla
np.random.seed(42)
fechas = pd.date_range('2002-10-28', '2004-03-13')
productos = ["Suavitel", "Fabuloso", "Axión", "Dawn"]
zonas = ["Bello", "Envigado", "Conquistadores", "San javier"]

# Simular 1000 registros
n = 1000
ventas = pd.DataFrame({
    'fecha': np.random.choice(fechas, 1000),
    'producto': np.random.choice(productos, 1000),
    'cantidad': np.random.randint(1, 10, 1000),
    'precio_unitario': np.random.randint(800, 5000, 1000),
    'zona': np.random.choice(zonas, 1000)
})

# Calcular ingreso por fila
ventas['ingreso'] = ventas['cantidad'] * ventas['precio_unitario']
print(ventas.head())

# Producto más vendido por zona
prod_zona = ventas.groupby(['zona', 'producto'])['cantidad'].sum().reset_index()
mas_vendido_zona = prod_zona.loc[prod_zona.groupby('zona')['cantidad'].idxmax()]
print("\nProducto más vendido por zona:")
print(mas_vendido_zona)

# Día del mes con más ingresos
ventas['dia'] = ventas['fecha'].dt.day
ingresos_dia = ventas.groupby('dia')['ingreso'].sum()
dia_max_ingresos = ingresos_dia.idxmax()
print("\nDía con más ingresos:")
print(dia_max_ingresos)


       fecha  producto  cantidad  precio_unitario        zona  ingreso
0 2003-02-07  Suavitel         7             1837    Envigado    12859
1 2004-01-06  Suavitel         1             4289  San javier     4289
2 2003-10-11     Axión         7             3434       Bello    24038
3 2003-07-25      Dawn         5             4783       Bello    23915
4 2003-02-11  Suavitel         6             2578  San javier    15468

Producto más vendido por zona:
              zona  producto  cantidad
0            Bello     Axión       398
6   Conquistadores  Fabuloso       402
8         Envigado     Axión       342
14      San javier  Fabuloso       308

Día con más ingresos:
17
